### ISSUE TITLE
Auto paste selected text into the Extension

### ISSUE THREAD

**Issue by Chinmay-KB** [Chinmay-KB/project-kopie#5]
### Issue
Currently the user has to paste the text into the text box of the extension popup to generate a QR.

### Enhancement
If the user has already copied some text, when they click on the extension icon, the text should already be pasted and the QR code, generated

**Comment by conruggles** [comment]
I can take this

**Comment by Chinmay-KB** [comment]
@all-contributors please add @Chinmay-KB for code

**Comment by Chinmay-KB** [comment]
@all-contributors please add @rugglcon for code
